vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        carousel_images:
            # alias for acced picture via navigator
            uri_prefix: /uploads/carousel
            # path stokage directory
            upload_destination: '%kernel.project_dir%/public/uploads/carousel'
            delete_on_update: true
            delete_on_remove: true


        products_images:
            # alias for acced picture via navigator
            uri_prefix: /uploads/products
            # path stokage directory
            upload_destination: '%kernel.project_dir%/public/uploads/products'
            delete_on_update: true
            delete_on_remove: true
